import React from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Button } from '@/components/ui/button';
import { Gamepad2, Sparkles, Zap, Play, Code, Users, BarChart3, Lightbulb, Palette, Puzzle, ToyBrick, MonitorSmartphone } from 'lucide-react';

const pageVariants = {
  initial: { opacity: 0, y: 20 },
  in: { opacity: 1, y: 0 },
  out: { opacity: 0, y: -20 },
};

const pageTransition = {
  type: "tween",
  ease: "anticipate",
  duration: 0.5,
};

const HomePage = () => {
  const features = [
    { icon: Palette, title: "AI-Powered Graphics", description: "Experience stunning visuals generated by advanced AI models." },
    { icon: Puzzle, title: "Unique Gameplay", description: "Discover novel game mechanics and procedurally generated content." },
    { icon: Lightbulb, title: "Creative Freedom", description: "Use AI tools to design and build your own games effortlessly." },
  ];

  return (
    <motion.div initial="initial" animate="in" exit="out" variants={pageVariants} transition={pageTransition}>
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-20 pb-16">
        <div className="text-center">
          <motion.div
            initial={{ scale: 0, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            transition={{ delay: 0.2, duration: 0.6, type: "spring", stiffness: 150 }}
            className="inline-flex items-center space-x-2 bg-gradient-to-r from-blue-500/20 to-purple-500/20 backdrop-blur-sm border border-white/20 rounded-full px-4 py-2 mb-8 shadow-lg"
          >
            <Sparkles className="h-5 w-5 text-yellow-300" />
            <span className="text-sm font-medium text-white/90">The Future of Gaming is Here</span>
            <Zap className="h-5 w-5 text-blue-300" />
          </motion.div>

          <motion.h1
            initial={{ y: 50, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            transition={{ delay: 0.4, duration: 0.8, ease: "easeOut" }}
            className="text-5xl md:text-7xl font-black mb-6 leading-tight"
          >
            <span className="gradient-text">AI Gaming Zone</span>
          </motion.h1>

          <motion.p
            initial={{ y: 30, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            transition={{ delay: 0.6, duration: 0.8, ease: "easeOut" }}
            className="text-xl md:text-2xl text-white/80 mb-10 max-w-3xl mx-auto font-medium"
          >
            Play and Create games made by AI. Dive into a universe of limitless possibilities.
          </motion.p>

          <motion.div
            initial={{ y: 30, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            transition={{ delay: 0.8, duration: 0.8, ease: "easeOut" }}
            className="flex flex-col sm:flex-row gap-4 justify-center items-center mb-6"
          >
            <motion.div whileHover={{ scale: 1.05, y: -3 }} whileTap={{ scale: 0.95 }}>
              <Link to="/games">
                <Button size="lg" className="bg-gradient-to-r from-blue-500 to-purple-600 hover:from-blue-600 hover:to-purple-700 text-white font-bold px-10 py-6 rounded-full text-lg pulse-glow shadow-xl hover:shadow-2xl transition-all">
                  <Play className="mr-2 h-6 w-6" />
                  Start Playing
                </Button>
              </Link>
            </motion.div>
            <motion.div whileHover={{ scale: 1.05, y: -3 }} whileTap={{ scale: 0.95 }}>
              <Link to="/create">
                <Button size="lg" variant="outline" className="border-white/30 text-white hover:bg-white/10 font-bold px-10 py-6 rounded-full text-lg backdrop-blur-sm shadow-xl hover:shadow-2xl transition-all">
                  <Code className="mr-2 h-6 w-6" />
                  Create Games
                </Button>
              </Link>
            </motion.div>
          </motion.div>
          
          <motion.div
            initial={{ y: 20, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            transition={{ delay: 1.0, duration: 0.7, ease: "easeOut" }}
            className="text-sm text-white/60 mb-20 flex items-center justify-center"
          >
            <MonitorSmartphone className="h-4 w-4 mr-2 text-blue-300" />
            <span>For the best experience, please play our games on a Desktop or Laptop.</span>
          </motion.div>
        </div>

        <motion.section 
          initial={{ opacity: 0, y: 50 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 1.2, duration: 0.8, ease: "easeOut" }}
          className="mb-24"
        >
          <h2 className="text-3xl md:text-4xl font-bold gradient-text mb-12 text-center">Why AI Gaming Zone?</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {features.map((feature, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 1.4 + index * 0.2, duration: 0.6 }}
                className="glass-effect rounded-2xl p-8 text-center hover:shadow-purple-500/30 shadow-lg transition-shadow duration-300"
              >
                <div className="p-4 bg-gradient-to-br from-blue-500/30 to-purple-500/30 inline-block rounded-full mb-6">
                  <feature.icon className="h-10 w-10 text-blue-300" />
                </div>
                <h3 className="text-2xl font-semibold text-white mb-3">{feature.title}</h3>
                <p className="text-white/70 text-sm">{feature.description}</p>
              </motion.div>
            ))}
          </div>
        </motion.section>
        
        <motion.div
          initial={{ scale: 0.9, opacity: 0 }}
          animate={{ scale: 1, opacity: 1 }}
          transition={{ delay: 1.4, duration: 1, ease: "easeOut" }}
          className="relative mx-auto max-w-5xl mb-24"
        >
          <div className="relative glass-effect rounded-3xl p-6 md:p-10 floating-animation shadow-2xl">
            <img  
              class="w-full h-auto md:h-[500px] object-cover rounded-2xl shadow-2xl border-2 border-purple-500/50" 
              alt="AI-generated gaming interface showcasing a vibrant fantasy world with futuristic elements and characters"
             src="https://images.unsplash.com/photo-1678995635432-d9e89c7a8fc5" />
            
            <motion.div
              animate={{ y: [0, -12, 0], rotate: [0, 3, 0, -3, 0] }}
              transition={{ duration: 5, repeat: Infinity, ease: "easeInOut" }}
              className="absolute -top-5 -left-5 bg-gradient-to-r from-blue-500 to-cyan-500 p-3 rounded-2xl shadow-xl"
            >
              <Gamepad2 className="h-8 w-8 text-white" />
            </motion.div>
            
            <motion.div
              animate={{ y: [0, 12, 0], rotate: [0, -3, 0, 3, 0] }}
              transition={{ duration: 4, repeat: Infinity, ease: "easeInOut", delay: 0.5 }}
              className="absolute -top-5 -right-5 bg-gradient-to-r from-purple-500 to-pink-500 p-3 rounded-2xl shadow-xl"
            >
              <Sparkles className="h-8 w-8 text-white" />
            </motion.div>
            
            <motion.div
              animate={{ y: [0, -10, 0], x: [0, 5, 0, -5, 0] }}
              transition={{ duration: 6, repeat: Infinity, ease: "easeInOut", delay: 1 }}
              className="absolute -bottom-5 left-1/2 transform -translate-x-1/2 bg-gradient-to-r from-green-500 to-emerald-500 p-3 rounded-2xl shadow-xl"
            >
              <Zap className="h-8 w-8 text-white" />
            </motion.div>
          </div>
        </motion.div>

        <motion.section
          initial={{ opacity: 0, y: 50 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 1.6, duration: 0.8, ease: "easeOut" }}
          className="grid grid-cols-1 md:grid-cols-3 gap-8 mt-20"
        >
          <div className="glass-effect rounded-2xl p-8 text-center shadow-lg hover:shadow-blue-500/30 transition-shadow duration-300">
            <Users className="h-10 w-10 text-green-400 mx-auto mb-4" />
            <div className="text-4xl font-bold gradient-text mb-2">1M+</div>
            <div className="text-white/70">Community Members</div>
          </div>
          <div className="glass-effect rounded-2xl p-8 text-center shadow-lg hover:shadow-pink-500/30 transition-shadow duration-300">
            <ToyBrick className="h-10 w-10 text-yellow-400 mx-auto mb-4" />
            <div className="text-4xl font-bold gradient-text mb-2">5000+</div>
            <div className="text-white/70">AI Generated Games</div>
          </div>
          <div className="glass-effect rounded-2xl p-8 text-center shadow-lg hover:shadow-purple-500/30 transition-shadow duration-300">
            <BarChart3 className="h-10 w-10 text-red-400 mx-auto mb-4" />
            <div className="text-4xl font-bold gradient-text mb-2">99.9%</div>
            <div className="text-white/70">Uptime & Reliability</div>
          </div>
        </motion.section>
      </div>
    </motion.div>
  );
};

export default HomePage;
